apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  name: ocp-installer
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  labels:
    app.kubernetes.io/part-of: ocp-installer
spec:
  forProvider:
    tags:
      Purpose: OpenShift-Installer
      CreatedBy: Crossplane
      Product: OpenShift
