---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: User
metadata:
  name: ocp-installer
  namespace: cluster-placeholder
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  labels:
    app.kubernetes.io/part-of: ocp-installer
spec:
  name: ocp-installer
  tags:
    - key: Purpose
      value: OpenShift-Installer
    - key: CreatedBy
      value: ACK
    - key: Product
      value: OpenShift
