---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: AccessKey
metadata:
  name: ocp-installer-access-key
  namespace: cluster-placeholder
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: ocp-installer
spec:
  userName: ocp-installer
